# Generated by Django 6.0.4 on 2026-04-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('men_single', 'Men Single'), ('men_doubles', 'Men Doubles'), ('women_single', 'Women Single'), ('women_doubles', 'Women Doubles'), ('mixed', 'Mixed')], max_length=30)),
                ('bracket_type', models.CharField(blank=True, choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin')], max_length=30, null=True)),
                ('team_count', models.IntegerField(blank=True, null=True)),
                ('bracket_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_label', models.CharField(max_length=10)),
                ('college', models.CharField(blank=True, choices=[('CAF', 'College of Agriculture and Forestry'), ('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CIT', 'College of Industrial Technology'), ('CTED', 'College of Teacher Education'), ('CCJE', 'College of Criminal Justice Education')], max_length=10, null=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.category')),
            ],
            options={
                'ordering': ['slot_label'],
                'unique_together': {('category', 'slot_label')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('round_number', models.IntegerField(default=1)),
                ('match_number', models.IntegerField(default=1)),
                ('bracket_slot', models.CharField(blank=True, max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('is_next_up', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.category')),
                ('participant_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='core.participant')),
                ('participant_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='core.participant')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basketball', 'Basketball'), ('softball', 'Softball'), ('badminton', 'Badminton'), ('sepak_takraw', 'Sepak Takraw'), ('chess', 'Chess'), ('table_tennis', 'Table Tennis'), ('volleyball', 'Volleyball'), ('soccer', 'Soccer')], max_length=50, unique=True)),
                ('facilitator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_sport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('sport', 'name')},
        ),
    ]
