# Generated by Django 6.0.4 on 2026-04-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('standby', 'Standby'), ('playing', 'Playing'), ('done', 'Done')], default='standby', max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.participant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
