# Generated by Django 6.0.4 on 2026-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_year', models.CharField(default='2026', max_length=10)),
                ('event_name', models.CharField(default='Intramurals', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='sport',
            name='facilitator_display_name',
            field=models.CharField(blank=True, help_text='Full name of the facilitator shown to viewers', max_length=100),
        ),
    ]
